name: cou-commerce-monitoring

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Linux에서 호스트 접근용 DNS 매핑
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--timeout=2", "http://localhost:9090/-/healthy"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - cou-commerce-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000" # React 개발 서버(3000)와의 충돌을 피해 3001로 변경
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin # Change this in production!
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--timeout=2", "http://localhost:3000/api/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - cou-commerce-net

volumes:
  grafana-data:

networks:
  cou-commerce-net:
    external: true
