name: cou-commerce-elk

services:
  elasticsearch:
    image: elasticsearch:7.17.3 # Use a specific version compatible with Logstash/Kibana
    container_name: elasticsearch
    environment:
      - discovery.type=single-node # For single-node development setup
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Adjust memory as needed
    ports:
      - "9200:9200" # HTTP
      - "9300:9300" # Transport
    volumes:
      - esdata:/usr/share/elasticsearch/data # Persistent data
    healthcheck:
      test: |
        CMD-SHELL curl -s http://localhost:9200/_cluster/health | grep -q '"status":"green"\|status":"yellow"'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - cou-commerce-net

  logstash:
    image: logstash:7.17.3 # Must match Elasticsearch version
    container_name: logstash
    ports:
      - "5044:5044" # For Filebeat input
      - "9600:9600" # For Logstash API (optional)
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf # Logstash config
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m # Adjust memory as needed
    depends_on:
      - elasticsearch # Ensure Elasticsearch is up before Logstash
    healthcheck:
      test: |
        CMD-SHELL curl -s http://localhost:9600/ | grep -q 'logstash'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - cou-commerce-net

  kibana:
    image: kibana:7.17.3 # Must match Elasticsearch version
    container_name: kibana
    ports:
      - "5601:5601" # Kibana UI
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # Connect to Elasticsearch service name
    depends_on:
      - elasticsearch # Ensure Elasticsearch is up before Kibana
    healthcheck:
      test: |
        CMD-SHELL curl -s http://localhost:5601/api/status | grep -q '"state":"green"'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - cou-commerce-net

  filebeat:
    image: elastic/filebeat:7.17.3 # Must match ELK stack version
    container_name: filebeat
    volumes:
      # Mount the application's log directory from the host into the Filebeat container
      - /Users/goorm/Desktop/team/Cou-commerce/logs:/usr/share/filebeat/logs:ro
      # Mount the filebeat.yml configuration file
      - ./filebeat-docker.yml:/usr/share/filebeat/filebeat.yml:ro
    command: ["filebeat", "-e", "-c", "/usr/share/filebeat/filebeat.yml"]
    depends_on:
      - logstash # Ensure Logstash is up before Filebeat starts sending logs
    networks:
      - cou-commerce-net

volumes:
  esdata: # Volume for Elasticsearch persistent data

networks:
  cou-commerce-net:
    external: true
