filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /usr/share/filebeat/logs/application.log
    - /usr/share/filebeat/logs/security.log
  fields:
    service: cou-commerce

output.logstash:
  hosts: ["logstash:5044"]
